include correct_iseli_z.praat

form log name
  sentence log log file name
endform

# procedure correct_iseli_z (f, fx, bx, fs)
# f: the frequency in question: f0 for H1, 2f0 for H2, etc.
# fx: the x-th formant frequency
# bx: the x-th formant bandwidth
# fs: the sampling frequency
# TODO: inputs generated by non-expert from madurese_voicesauce_formulabw
@correct_iseli_z: 125.836, 1375.192, 149.329, 1000
appendFileLine: log$, correct_iseli_z.result
delta = 1e-14
assert abs(1.5090311725669858 - correct_iseli_z.result) < delta
